export const symptomOptions = [
  "Fatigue",
  "Low energy",
  "Brain fog",
  "Poor concentration",
  "Weight gain",
  "Difficulty losing weight",
  "Increased appetite",
  "Cravings",
  "Difficulty sleeping",
  "Snoring",
  "Wake unrefreshed",
  "Anxiety",
  "Depression",
  "Low libido",
  "Erectile dysfunction",
  "Hot flashes",
  "Night sweats",
  "Joint pain",
  "Muscle pain",
  "Bloating",
  "Constipation",
  "Reflux",
];

export const medicalConditionOptions = [
  "High blood pressure",
  "High cholesterol",
  "Heart disease",
  "Arrhythmia",
  "Stroke",
  "Type 1 diabetes",
  "Type 2 diabetes",
  "Prediabetes",
  "Thyroid disorder",
  "PCOS",
  "Asthma",
  "COPD",
  "Sleep apnea",
  "Migraines",
  "Anxiety",
  "Depression",
  "ADHD",
  "Autoimmune disease",
];

export const familyHistoryOptions = [
  "Father - Heart disease",
  "Mother - Heart disease",
  "Sibling - Heart disease",
  "Father - Diabetes",
  "Mother - Diabetes",
  "Sibling - Diabetes",
  "Father - Cancer",
  "Mother - Cancer",
  "Sibling - Cancer",
  "Father - Dementia/Alzheimer’s",
  "Mother - Dementia/Alzheimer’s",
  "Sibling - Dementia/Alzheimer’s",
];

export const serviceOptions = [
  "Hormone Optimization",
  "Medical Weight Loss",
  "GLP-1 Programs",
  "Peptide Therapy",
  "Functional Medicine",
  "NAD+ Therapy",
  "IV Therapy",
];
